### ISSUE TITLE
yo angular-require:route extrawork throws new type error

### ISSUE THREAD

**Issue by Yves-T** [aaronallport/generator-angular-require#45]
When I'm trying to create a route I get following error:

yo angular-require:route extrawork

path.js:360
        throw new TypeError('Arguments to path.join must be strings');
        ^
TypeError: Arguments to path.join must be strings
    at path.js:360:15
    at Array.filter (native)
    at Object.exports.join (path.js:358:36)
    at new ScriptBase.extend.constructor (/usr/local/lib/node_modules/generator-angular-require/route/index.js:15:12)
    at Environment.instantiate (/usr/local/lib/node_modules/yo/node_modules/yeoman-generator/lib/env/index.js:267:10)
    at Environment.create (/usr/local/lib/node_modules/yo/node_modules/yeoman-generator/lib/env/index.js:244:15)
    at Environment.run (/usr/local/lib/node_modules/yo/node_modules/yeoman-generator/lib/env/index.js:303:24)
    at init (/usr/local/lib/node_modules/yo/cli.js:114:7)
    at pre (/usr/local/lib/node_modules/yo/cli.js:133:3)
    at Object.<anonymous> (/usr/local/lib/node_modules/yo/cli.js:163:1)

**Comment by Metoyo** [comment]
Hi @aaronallport I'm getting this error too for generating service.

**Comment by aaronallport** [comment]
Version 0.4.1 of the generator is out - may I ask that you test using that version please? If you still get the error after upgrading, please paste me the output. I'm unable to re-create this using 0.4.1

Thanks!

**Comment by aaronallport** [comment]
Are folks still having this issue?

**Comment by Metoyo** [comment]
The latest version has no error.

**Comment by aaronallport** [comment]
Great - thanks for confirming!
