### ISSUE TITLE
yo angular-require [project name] installation error

### ISSUE THREAD

**Issue by Vittalks** [aaronallport/generator-angular-require#73]
module.js:340
    throw err;
          ^
Error: Cannot find module 'ejs'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at new yeoman.Base.extend.constructor (/home/yoobikwitid2/.nvm/v0.10.25/lib/node_modules/generator-angular-require/app/index.js:19:19)
    at Environment.instantiate (/home/yoobikwitid2/.nvm/v0.10.25/lib/node_modules/yo/node_modules/yeoman-environment/lib/environment.js:328:10)
    at Environment.create (/home/yoobikwitid2/.nvm/v0.10.25/lib/node_modules/yo/node_modules/yeoman-environment/lib/environment.js:305:15)
    at Environment.run (/home/yoobikwitid2/.nvm/v0.10.25/lib/node_modules/yo/node_modules/yeoman-environment/lib/environment.js:364:24)
    at /home/yoobikwitid2/.nvm/v0.10.25/lib/node_modules/yo/lib/cli.js:140:11
    at Array.forEach (native)

**Comment by Vittalks** [comment]
Need to install npm module global
npm install -g ejs
